# Generated by Django 4.0.6 on 2022-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_logtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='hit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
